# Blog settings
permalink: /blog/:title.html
# host: 0.0.0.0

# My variables
name: YSMull
description: YSMull的个人博客
baidu_verification: false

#timezone: Asia/Shanghai
timezone: +0800

# File management
exclude: [
  ".idea/*",
  "README.md",
  "assets/yarn.lock",
  "assets/node_modules/",
  "assets/entry.js",
  "assets/webpack.config.js",
#  "assets/css/",
  "assets/plugins",
  "assets/package.json",
#  "assets/font",
  "./upload.sh",
  "CNAME"
]
include: [
  "assets/build",
  "assets/js",
  "assets/css",
  "assets/font"
]

author:
  name: 简单小煜
  email: ysmull@aliyun.com
  link: ysmull.cn
future: true
# Sass
# sass:
#   style: :compressed
#   sass_dir: _sass


# Markdown
highlighter: rouge
markdown: kramdown
kramdown:
  MathJax: true
  syntax_highlighter: rouge
  math_engine: mathjax
  auto_ids:       true
  auto_id_prefix: 'id-'
  toc_levels:     '2,3,4'
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: true

collections:
  pages:
    output: true
    layout: post
    permalink: /:path/
  algorithms:
    output: true
    layout: post
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "algorithms"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "post"

url: "https://ysmull.cn"
plugins:
  - jekyll-sitemap
  - jekyll-feed

feed:
  path: atom.xml
